---
abstract: 'Lazy typing access to RDF data'
author:
  - 'Jakob Voß <voss@gbv.de>'
build_requires:
  Data::Dumper: 0
  English: 0
  RDF::Trine::Parser: 0
  Template: 0
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-Lazy
requires:
  CGI: 0
  Carp: 0
  RDF::Trine: 0
  RDF::Trine::Model: 0
  RDF::Trine::NamespaceMap: 0
  RDF::Trine::Serializer::Turtle: 0
  Scalar::Util: 0
  overload: 0
resources:
  bugtracker: https://github.com/nichtich/RDF-Lazy/issues
  repository: https://github.com/nichtich/RDF-Lazy
version: 0.062
